name: bqplot-gl-test
channels:
    - conda-forge
dependencies:
    - pip
    - python
    - python-build
    - yarn
    - ipywidgets
    - traitlets
    - traittypes
    - numpy
    - pandas
    - bqscales>=0.3.2
    - scipy
    - notebook
    - jupyterlab
    - jupyter-packaging # to build the wheel
    - pytest
    - nbval
    - pytest-cov
    - selenium
    - flake8
    - nose
